In [1]:
import numpy as np

In [3]:
array=np.arange(12)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
reshape1 = array.reshape(2,3,2)
reshape1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [10]:
reshape2 = np.reshape(array, (2,-1), order='F') #2행으로 변경, order='C'는 디폴트 값으로 왼쪽에서 오른쪽으로 order="F"는 위에서 아래
reshape2

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

## newaxis함수를 사용하여 배열의 차원을 증가시킴

In [13]:
array2 = np.arange(4)

axis1 = array2[np.newaxis]
axis1

array([[0, 1, 2, 3]])

In [15]:
axis2 = array2[:, np.newaxis]
axis2

array([[0],
       [1],
       [2],
       [3]])

## 배열의 차원을 축소시킴

In [16]:
array3 = np.arange(12).reshape(3,-1)
array3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
flatten1=array3.flatten(order="F") #order순으로 flatten으로 만듦(Fortran스타일로 변경)
flatten1

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [20]:
flatten2=array3.ravel() #order 레이아웃을 C스타일로 변경
flatten2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 배열 병합(stack()) 및 분리(split())

In [23]:
array1 = np.arange(6).reshape(2,3)
array2 = np.arange(6,12).reshape(2,3)
print(array1)
print(array2)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [26]:
merge1 = np.stack([array1, array2], axis=0) #1번쨰 차원을 기준으로 삽입
print(merge1)
print(merge1.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)


In [29]:
merge2 = np.stack([array1, array2], axis=-1) #맨 마지막번쨰 차원을 기준으로 삽입함
print(merge2)
print(merge2.shape)

[[[ 0  6]
  [ 1  7]
  [ 2  8]]

 [[ 3  9]
  [ 4 10]
  [ 5 11]]]
(2, 3, 2)


In [31]:
array = np.arange(10).reshape(2,5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
detach1 = np.split(array, 2, axis=0) #indeX의 개수만큼 나눔.
detach1

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

In [36]:
detach2 = np.split(array, (2,3), axis=1)#array[2:3]을 기준으로 나눔
detach2

[array([[0, 1],
        [5, 6]]),
 array([[2],
        [7]]),
 array([[3, 4],
        [8, 9]])]

In [37]:
np.mat(array) #매트릭스함수로 변경

matrix([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [39]:
array3 = np.arange(10)
np.mat(array3)

matrix([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])