# 영상 필터

In [20]:
# 평균값을 적용하여 이미지를 흐릿하게 함
import cv2
import numpy as np

img = cv2.imread("./img/girl.jpg")

kernel1 = np.array([[0.04, 0.04, 0.04, 0.04, 0.04],
                  [0.04, 0.04, 0.04, 0.04, 0.04],
                  [0.04, 0.04, 0.04, 0.04, 0.04],
                  [0.04,0.04, 0.04, 0.04, 0.04],
                  [0.04,0.04,0.04,0.04,0.04]])
kernel2 = np.ones((5,5))/5**2
print("kernel2: ", kernel2)
blured1 = cv2.filter2D(img, -1, kernel1)
blured2 = cv2.filter2D(img, -1, kernel2)
merged=np.hstack((img, blured1, blured2))
cv2.imshow("merged", merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

kernel2:  [[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


In [18]:
## 직접 커널을 생성하지 않고, 평균 블러를 할 수 있도록 하는 함수 사용

img = cv2.imread("./img/taekwonv1.jpg")

#blur함수 사용
blur1 = cv2.blur(img, (10,10))
#boxFilter함수 사용
blur2 = cv2.boxFilter(img, -1, (10,10))

merged=np.hstack((img, blur1, blur2))
cv2.imshow("merged", merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [50]:
##  가우시안 블러

img = cv2.imread("./img/gaussian_noise.jpg")
k1 = np.array([[1,2,1],
              [2,4,2],
              [1,2,1]]) *(1/16)

blur1 = cv2.filter2D(img, -1, k1)
print("k1:", k1)

# 가우시안 커널을 API로 얻어서 블러링
k2=cv2.getGaussianKernel(3,0)
blur2=cv2.filter2D(img, -1, k2*k2.T)
print("k2:", k2)
print("k2.T:", k2.T)

#가우시안 블러 API로 얻어서 블러링
blur3=cv2.GaussianBlur(img, (3,3), 0)

merged=np.hstack((img, blur1, blur2, blur3))
cv2.imshow("merged", merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

k1: [[0.0625 0.125  0.0625]
 [0.125  0.25   0.125 ]
 [0.0625 0.125  0.0625]]
k2: [[0.25]
 [0.5 ]
 [0.25]]
k2.T: [[0.25 0.5  0.25]]


In [35]:
# 미디언 블러링 (중간 값을 대상 픽셀의 값으로 선택하는 미디언 블러링)

img = cv2.imread("./img/salt_pepper_noise.jpg")

#미디언 블러 적용
blur = cv2.medianBlur(img, 25)

merged=np.hstack((img, blur))
cv2.imshow("merged", merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [44]:
## 바이레터럴 필터와 가우시안 필터 비교

img = cv2.imread("./img/gaussian_noise.jpg")

#가우시안
blur1 = cv2.GaussianBlur(img, (5,5), 0)

#바이레터럴 필터
blur2 = cv2.bilateralFilter(img, 5, 75, 75)

merged=np.hstack((img, blur1, blur2))
cv2.imshow("merged", merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 기본 경계검출

In [60]:
#기본 미분 필터

img = cv2.imread("./img/sudoku.jpg")

#기본 미분
gx_kernel = np.array([[-1,1]])
gy_kernel = np.array([[-1],[1]])

#필터 적용
edge_gx = cv2.filter2D(img, -1, gx_kernel)
edge_gy = cv2.filter2D(img, -1, gx_kernel)

merged=np.hstack((img, edge_gx, edge_gy))
cv2.imshow("merged", merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [61]:
## 로버츠 교차 필터(기본 미분 필터를 개선한 커털을 제안함) = 대각선 방향으로 1과 -1을 배치하여 사선 경계 검출 효과를 높암

img = cv2.imread("./img/sudoku.jpg")

gx_kernel = np.array([[1,0],[0,-1]])
gy_kernel = np.array([[0,1],[-1,0]])

edge_gx=cv2.filter2D(img, -1, gx_kernel)
edge_gy = cv2.filter2D(img, -1, gy_kernel)

merged = np.hstack((img, edge_gx, edge_gy, edge_gx + edge_gy))
cv2.imshow("merged", merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [62]:
# 프리윗 필터(각 방향으로 차분을 세번 계산하도록 배치...) = 대각선 검출이 약하다..

img = cv2.imread("./img/sudoku.jpg")

gx_k = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
gy_k = np.array([[-1,-1,-1],[0,0,0],[1,1,1]])

edge_gx = cv2.filter2D(img, -1, gx_k)
edge_gy = cv2.filter2D(img, -1, gy_k)

merged = np.hstack((img, edge_gx, edge_gy, edge_gx + edge_gy))
cv2.imshow("prewitt cross", merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [70]:
## 소벨필터(중심 픽셀의 차분 비중을 두배로 주어 수평, 수직,대각선 경계  검출에 모두 강힌 마스트를 제안합니다)

img = cv2.imread("./img/sudoku.jpg")

#소벨커널 생성
gx_k = np.array([[-1,0,1],[-2,0,2],[-1,0,1]])
gy_k = np.array([[-1,-2,-1],[0,0,0],[1,2,1]])

edge_gx = cv2.filter2D(img, -1, gx_k)
edge_gy = cv2.filter2D(img, -1, gy_k)

# sobel API 생성
sobelx = cv2.Sobel(img, -1, 2, 0, ksize=3)
sobely = cv2.Sobel(img, -1, 0,2, ksize=3)

merged1 = np.hstack((img, edge_gx, edge_gy, edge_gx + edge_gy))
merged2 = np.hstack((img, sobelx, sobely, sobelx+sobely))
merged3=np.vstack((merged1, merged2))
cv2.imshow("sobel", merged3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [74]:
## 샤르 필터

img = cv2.imread("./img/sudoku.jpg")

gx_k = np.array([[-3,0,3],[-10,0,10],[-3,0,3]])
gy_k = np.array([[-3, -10, -3], [0,0,0],[3,10,3]])

edge_gx = cv2.filter2D(img,-1, gx_k)
edge_gy = cv2.filter2D(img, -1, gy_k)

scharrx = cv2.Scharr(img, -1, 1,0)
scharry = cv2.Scharr(img, -1, 0,1)

merged1 = np.hstack((img, edge_gx, edge_gy))
merged2 = np.hstack((img, scharrx, scharry))
merged3=np.vstack((merged1, merged2))
cv2.imshow("sobel", merged3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [75]:
## 라플라이사인 필터(2차 미분)

img = cv2.imread("./img/sudoku.jpg")
edge=cv2.Laplacian(img, -1)

merged = np.hstack((img, edge))
cv2.imshow("Laplacian", merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [88]:
## 캐니 엣지 (4단계) = 노이즈 제거(가우시안 필터), 그레이디언트 방향 검출, 비최대치 억제... 등
# 특히 스레시홀드값의 지정에 따라 경계검출 대상을 조정할 수 있어서 가장 많이 사용되는 함수임.

img = cv2.imread("./img/sudoku.jpg")

edges=cv2.Canny(img, 100,200) #스레시 홀드의 값(최대값 최소값)을 지정하여 경계 검출 대상 조정이 가능함

cv2.imshow("Laplacian", edges)
cv2.imshow("original", img)
cv2.waitKey(0)
cv2.destroyAllWindows()